/*
 * @file    main.c
 * @brief   Implementation file for the main module.
 * @details This file contains the implementation of the main module, including
 *          the main function, initialization functions, and other utility functions.
 *          It also includes necessary headers and sections for function prototypes,
 *          definitions, enums, structs/unions, and global variables.
 * @author  Chipsbank
 * @date    2024
 */

/*
 * Hardware Connections: UART GPIO00-RX, GPIO01-TX
 *
 * Program Flow:
 *     1. Initialize UART and configure UART parameters: BPR=115200, Stop bit = 1, BitOrder = LSB, Parity = NONE
 *     2. Generate random numbers based on noise and print them via UART
 *     3. Generate a one-time random number without a seed and print it via UART
 *     4. Generate random numbers based on input and print them via UART
 * Expected Output:
 *     1. After power-on, the UART prints a power-on reset message
 *     2. It then prints random numbers generated by the three different methods
 *     3. Power on multiple times to observe if the generated numbers are truly random
 *        (Only the numbers generated based on noise are truly random; others are pseudo-random generated by algorithms/inputs)
 */
//-------------------------------
// INCLUDE SECTION
//-------------------------------
#include "main.h"

//-------------------------------
// FUNCTION BODY SECTION
//-------------------------------
/**
 * @brief The main function of the program.
 * 
 * This function serves as the entry point of the program. It is called automatically
 * when the program starts executing. The function contains an infinite loop, which
 * ensures that the program continues running indefinitely.
 * 
 * @return An integer value representing the exit status of the program. 
 *         This function always returns 0, indicating successful execution.
 */
int main(void)
{ 
    //Trng demo                    
    app_peripheral_trng_init();
    while(1);
}
